### ISSUE TITLE
nil evaluation needed?

### ISSUE THREAD

**Issue by joecabezas** [douglasmakey/go-fcm#2]
https://github.com/douglasmakey/go-fcm/blob/acbbebae3da098906796474c78c5425449fcb27d/fcm.go#L250

not familiar with go, but nil is not evaluated already as false?, in that case there is no need to evaluate
```
if a == nil
```
instead

```
if a
```

**Comment by patrickdappollonio** [comment]
Go doesn't have the concept of truth-y or false-y like Javascript or other untyped languages.

Saludos perro!

**Comment by patrickdappollonio** [comment]
Oh, BTW, line 242 is indeed not checking for the error. I guess that may be a bug worth to check out. :+1:

**Comment by douglasmakey** [comment]
@patrickdappollonio I didn't see that I did not check for the error in line 242, thanks, master :D

**Comment by joecabezas** [comment]
you welcome prro!
